### PR TITLE
Pass in remote as argument to docker build script

### PR DESCRIPTION
**Pull request by audrow**
After this works, I'll set this up for [robotpt/cordial](https://github.com/robotpt/cordial).

Also, I forked our repo to confirm that CI worked with external PRs.

### CODE REVIEW

**Comment by audrow** [comment]
Currently this is failing because the secret AWS credentials aren't being passed in. It turns out that this requires [sharing secrets with external contributors](https://github.community/t/feature-request-allow-secrets-in-approved-external-pull-requests/18071). I'm still looking for a good way to run tests from external contributors.

**Comment by audrow** [comment]
@emilyxzhou, what do you think of this approach? It turns out that I can't use secrets on external PRs because either direction of sharing secrets represents a security threat. Instead, I split up the testing scripts to avoid testing things that require secrets on pr events. Push and scheduled events still run the tests that require secrets (AWS credentials).

This PR also makes the tests more general so that they use whatever repository, aka the tests now work with forked versions of this repo.

**Review by emilyxzhou — APPROVED** [review]
@audrow, looks like a good solution to the security issues! It would be good to still run the full test script for internal PRs (if it's possible to differentiate between internal and external PRs), in the case that we want to test AWS services while developing the controller.

**Comment by audrow** [comment]
> It would be good to still run the full test script for internal PRs

This should be working. Internal PRs will have two events run on them: push and PR. The push event will run the full CI.

**Pull request merged**
